import type { ViolationFixture } from '../@types/index.js';

const LIB = 'packages/core/sample/src/lib';

/** По одной фикстуре на каждое правило из E00.02 (пункт 3), проверяемое без Angular. */
export const VIOLATION_FIXTURES: readonly ViolationFixture[] = [
    {
        name: 'форматирование: отступ 2 пробела и двойные кавычки',
        rule: 'format',
        file: `${LIB}/format.ts`,
        content: 'export function greet(name: string): string {\n  return "hi " + name;\n}\n',
        expectedRules: ['format'],
    },
    {
        name: 'interface вместо type',
        rule: 'consistent-type-definitions',
        file: `${LIB}/shape.ts`,
        content: 'export interface Shape {\n    size: number;\n}\n',
        expectedRules: ['@typescript-eslint/consistent-type-definitions'],
    },
    {
        name: 'импорт типа без import type',
        rule: 'consistent-type-imports',
        file: `${LIB}/importer.ts`,
        content:
            "import { Shape } from './shape.js';\n\nexport function area(shape: Shape): number {\n    return shape.size;\n}\n",
        expectedRules: ['lint/style/useImportType'],
    },
    {
        name: 'any',
        rule: 'no-explicit-any',
        file: `${LIB}/any.ts`,
        content: 'export function identity(value: any): unknown {\n    return value;\n}\n',
        expectedRules: ['lint/suspicious/noExplicitAny'],
    },
    {
        name: 'export const не в UPPER_CASE',
        rule: 'naming: export const',
        file: `${LIB}/export-const.ts`,
        content: 'export const maxRetryCount: number = 3;\n',
        expectedRules: ['@typescript-eslint/naming-convention'],
    },
    {
        name: 'private без двойного подчёркивания',
        rule: 'naming: private',
        file: `${LIB}/private.ts`,
        content:
            'export class Store {\n    private cache: number = 1;\n\n    public read(): number {\n        return this.cache;\n    }\n}\n',
        expectedRules: ['@typescript-eslint/naming-convention'],
    },
    {
        name: 'protected без подчёркивания',
        rule: 'naming: protected',
        file: `${LIB}/protected.ts`,
        content: 'export class Base {\n    protected attempts: number = 0;\n}\n',
        expectedRules: ['@typescript-eslint/naming-convention'],
    },
    {
        name: 'public с подчёркиванием',
        rule: 'naming: public',
        file: `${LIB}/public.ts`,
        content: 'export class Cart {\n    public _items: number = 0;\n}\n',
        expectedRules: ['@typescript-eslint/naming-convention'],
    },
    {
        name: 'тип не в PascalCase',
        rule: 'naming: types',
        file: `${LIB}/type-name.ts`,
        content: 'export type orderDto = {\n    id: string;\n};\n',
        expectedRules: ['@typescript-eslint/naming-convention'],
    },
    {
        name: 'экспорт функции через export const',
        rule: 'naming: exported-functions',
        file: `${LIB}/arrow.ts`,
        content: 'export const run = (): number => 1;\n',
        expectedRules: ['no-restricted-syntax'],
    },
    {
        name: 'метод раньше поля',
        rule: 'member-ordering',
        file: `${LIB}/order.ts`,
        content:
            "export class Order {\n    public total(): number {\n        return 1;\n    }\n\n    public id: string = '';\n}\n",
        expectedRules: ['@typescript-eslint/member-ordering'],
    },
    {
        name: 'член без модификатора доступа',
        rule: 'explicit-member-accessibility',
        file: `${LIB}/accessibility.ts`,
        content: 'export class Cart {\n    items: number = 0;\n}\n',
        expectedRules: ['@typescript-eslint/explicit-member-accessibility'],
    },
    {
        name: 'метод без типа результата',
        rule: 'explicit-function-return-type',
        file: `${LIB}/return-type.ts`,
        content: 'export class Cart {\n    public count() {\n        return 1;\n    }\n}\n',
        expectedRules: ['@typescript-eslint/explicit-function-return-type'],
    },
    {
        name: 'поле без типа',
        rule: 'typedef',
        file: `${LIB}/typedef.ts`,
        content: 'export class Cart {\n    public items = 0;\n}\n',
        expectedRules: ['@typescript-eslint/typedef'],
    },
    {
        name: 'export default',
        rule: 'no-default-export',
        file: `${LIB}/default.ts`,
        content: 'const value: number = 1;\nexport default value;\n',
        expectedRules: ['no-restricted-syntax'],
    },
    {
        name: 'export *',
        rule: 'no-export-all',
        file: `${LIB}/star.ts`,
        content: "export * from './shape.js';\n",
        expectedRules: ['no-restricted-syntax'],
    },
    {
        name: 'Angular Material вне ui-web',
        rule: 'angular: material-allowed-in',
        file: `${LIB}/material.ts`,
        content: "import { MatButton } from '@angular/material/button';\n\nexport const BUTTON: unknown = MatButton;\n",
        expectedRules: ['no-restricted-imports'],
    },
];

/** Файлы, которые раннер обязан пропустить без замечаний. */
export const CLEAN_FIXTURES: readonly ViolationFixture[] = [
    {
        name: 'код по конвенциям',
        rule: 'все правила',
        file: `${LIB}/clean.ts`,
        content: [
            "import type { Shape } from './shape.js';",
            '',
            'export const MAX_RETRY_COUNT: number = 3;',
            '',
            'export type OrderDto = {',
            '    id: string;',
            '};',
            '',
            'export class OrderService {',
            '    public static readonly DEFAULT_LIMIT: number = 10;',
            '',
            '    public limit: number = OrderService.DEFAULT_LIMIT;',
            '',
            '    protected _attempts: number = 0;',
            '',
            '    private readonly __cache: Map<string, OrderDto> = new Map();',
            '',
            '    constructor(limit: number) {',
            '        this.limit = limit;',
            '    }',
            '',
            '    public getOrder(id: string): OrderDto | undefined {',
            '        return this.__cache.get(id) ?? this._load(id);',
            '    }',
            '',
            '    public measure(shape: Shape): number {',
            '        return shape.size;',
            '    }',
            '',
            '    protected _load(id: string): OrderDto | undefined {',
            '        this._attempts += 1;',
            '        return id ? { id } : undefined;',
            '    }',
            '}',
            '',
        ].join('\n'),
        expectedRules: [],
    },
    {
        name: 'Material внутри ui-web',
        rule: 'angular: material-allowed-in',
        file: 'packages/ui/ui-web/src/lib/button.ts',
        content: "import { MatButton } from '@angular/material/button';\n\nexport const BUTTON: unknown = MatButton;\n",
        expectedRules: [],
    },
];
